services:

  database:
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
    ports:
      - 127.0.0.1:5432:5432

  s3:
    volumes:
      - minio_data_dev:/data
    ports:
      - 127.0.0.1:9000:9000
      - 127.0.0.1:9001:9001

volumes:
  postgres_data_dev:
    driver: local
  minio_data_dev:
    driver: local

networks:
  default:
    name: telebot-dev
